// Run with: node --test scripts/*.test.js
const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const Coffee = require("../assets/js/coffee-recipe.js");
const Match = require("../assets/js/match-probabilities-data.js");
// Captured from the pre-refresh, inline calculators, not generated by the new modules.
const fixtures = require("./fixtures/calculator-legacy.json");

test("existing coffee profiles are preserved after the approved age-band shift and grind cap", () => {
  for (const { input, expected } of fixtures.coffee) {
    // Legacy fixtures remain unchanged: compare equivalent age profiles, not the
    // same day number now that the owner has moved the thresholds.
    const daysRoasted = input.daysRoasted <= 7 ? 7 : input.daysRoasted <= 20 ? 28 : 49;
    assert.deepEqual(
      Coffee.calculate({ ...input, daysRoasted }),
      { ...expected, grind: Math.max(-16, Math.min(expected.grind, 16)) },
      JSON.stringify(input)
    );
  }
});

test("three roast-age recipes preserve boundaries and do not mutate the selection", () => {
  const inputs = { roast: "medium", tastingNotes: ["Lemon"], daysRoasted: 50 };
  const before = JSON.stringify(inputs);
  const result = Coffee.compare(inputs);
  assert.deepEqual(
    result.map((r) => r.id),
    ["fresh", "rested", "aged"]
  );
  assert.equal(JSON.stringify(inputs), before);
  for (const [index, days] of [
    [0, [0, 7, 8, 13, 13.99]],
    [1, [14, 20, 21, 28, 41, 42]],
    [2, [42.01, 43, 49, 100]],
  ]) {
    for (const daysRoasted of days) assert.deepEqual(result[index].recipe, Coffee.calculate({ ...inputs, daysRoasted }));
  }
});

test("the aged medium-roast profile retains its existing temperature ordering", () => {
  const [fresh, rested, aged] = Coffee.compare({ roast: "medium" }).map((r) => r.recipe);
  assert.deepEqual([fresh.pulseTemps[0], rested.pulseTemps[0], aged.pulseTemps[0]], [95, 96, 88]);
  assert.equal(aged.bloomTemp, 87);
  assert.equal(aged.pulses, 5);
  assert.equal(Coffee.calculate({ roast: "medium", daysRoasted: 42 }).bloomTemp, 96);
  assert.equal(Coffee.calculate({ roast: "medium", daysRoasted: 43 }).bloomTemp, 87);
});

test("all offered roast/process combinations keep finite values and a temperature for every pulse", () => {
  for (const roast of Coffee.ROASTS) {
    for (const processing of [
      "",
      "Washed",
      "Monsooned",
      "Natural",
      "Honey White",
      "Honey Yellow",
      "Honey Red",
      "Honey Black",
      "Anaerobic",
      "Carbonic",
      "Wet-Hulled",
      "Pulped Natural",
      "Double Fermentation",
    ]) {
      for (const altitude of [null, 0, 1199, 1200, 1500, 1501, 2500]) {
        for (const { recipe } of Coffee.compare({
          roast,
          processing,
          altitude,
          tastingNotes: ["Lemon", "Jasmine", "Chocolate Dark", "Brown Sugar", "Cream", "Caramel"],
        })) {
          for (const value of Object.values(recipe).flat()) assert.ok(Number.isFinite(value));
          assert.equal(recipe.pulseTemps.length, recipe.pulses);
          assert.ok(recipe.brewRatio >= 14 && recipe.brewRatio <= 20);
          assert.ok(recipe.bloomRatio >= 1 && recipe.bloomRatio <= 3);
          assert.ok(recipe.grind >= -16 && recipe.grind <= 16);
          for (const t of [recipe.bloomTemp, ...recipe.pulseTemps]) assert.ok(t >= 50 && t <= 99);
        }
      }
    }
  }
});

test("grind is capped in both directions without changing ordinary adjustments", () => {
  assert.equal(Coffee.calculate({ roast: "light", processing: "Washed", altitude: 1700, daysRoasted: 7, tastingNotes: ["Lemon"] }).grind, -16);
  assert.equal(
    Coffee.calculate({
      roast: "dark",
      processing: "Wet-Hulled",
      altitude: 1100,
      daysRoasted: 49,
      tastingNotes: ["Chocolate Dark", "Walnut", "Jasmine"],
    }).grind,
    16
  );
  assert.equal(Coffee.calculate({ roast: "medium", daysRoasted: 28, tastingNotes: ["Lemon"] }).grind, -8);
});

test("the Fellow bloom-ratio limit and the existing hot dark-roast bloom are retained", () => {
  for (const daysRoasted of [7, 28, 49]) {
    assert.equal(
      Coffee.calculate({ roast: "light", country: "Brazil", altitude: 1700, processing: "Natural", daysRoasted, tastingNotes: ["Jasmine"] })
        .bloomRatio,
      3
    );
  }
  for (const daysRoasted of [7, 28, 42]) assert.equal(Coffee.calculate({ roast: "dark", daysRoasted }).bloomTemp, 99);
  assert.equal(Coffee.calculate({ roast: "dark", daysRoasted: 43 }).bloomTemp, 87);
});

test("several descriptors for the same traits do not multiply recipe adjustments", () => {
  const recipe = (tastingNotes) => Coffee.calculate({ roast: "medium", daysRoasted: 28, tastingNotes });
  assert.deepEqual(recipe(["Lemon"]), recipe(["Lemon", "Lime", "Orange", "Mandarin"]));
  assert.deepEqual(recipe(["Blueberry"]), recipe(["Blueberry", "Raspberry", "Blackcurrant", "Blackberry"]));
  assert.deepEqual(recipe(["Almond"]), recipe(["Almond", "Hazelnut", "Cashew", "Pecan", "Pistachio"]));
  assert.deepEqual(recipe(["Cedar"]), recipe(["Cedar", "Moss", "Mushroom", "Smoke", "Rum", "Yeast", "Cinnamon"]));
  assert.deepEqual(recipe(["Caramel"]), recipe(["Caramel", "Toffee", "Butterscotch", "Cedar"]));
  assert.deepEqual(recipe(["Lemon", "Lemon"]), recipe(["Lemon"]));
});

test("formerly unused notes change only the final pulse by one degree", () => {
  for (const roast of Coffee.ROASTS)
    for (const daysRoasted of [7, 28, 49]) {
      const inputs = { roast, daysRoasted };
      const base = Coffee.calculate(inputs);
      const expected = { ...base, pulseTemps: base.pulseTemps.map((t, i) => (i === base.pulses - 1 ? t - 1 : t)) };
      for (const note of ["Cedar", "Fermented Fruit", "Moss", "Mushroom", "Red Wine", "Rum", "Smoke", "Toast", "Yeast"]) {
        assert.deepEqual(Coffee.calculate({ ...inputs, tastingNotes: [note] }), expected, note);
      }
    }
});

test("Other choices apply the broad family rule without doubling an existing match", () => {
  for (const [other, specific] of [
    ["Other Fruity", "Blueberry"],
    ["Other Nutty & Chocolate", "Almond"],
    ["Other Sweet & Caramel", "Caramel"],
    ["Other Floral & Herbal", "Basil"],
    ["Other Creamy", "Butter"],
    ["Other Earthy & Roasted", "Cedar"],
    ["Other Fermented & Wine-like", "Rum"],
    ["Other Spiced", "Cinnamon"],
  ]) {
    const input = { roast: "medium", daysRoasted: 28, tastingNotes: [specific] };
    assert.deepEqual(Coffee.calculate(input), Coffee.calculate({ ...input, tastingNotes: [specific, other] }), other);
  }
});

test("every offered tasting note has an effect and every family has an Other choice", () => {
  const page = fs.readFileSync(path.join(__dirname, "../_pages/brewcoffee.md"), "utf8");
  const notes = [...page.matchAll(/name="tastingNotes" value="([^"]+)"/g)].map((m) => m[1].replaceAll("&amp;", "&"));
  assert.equal(notes.length, 83);
  assert.equal(new Set(notes).size, notes.length);
  assert.equal(notes.filter((note) => note.startsWith("Other ")).length, 8);
  const base = Coffee.calculate({ roast: "medium", daysRoasted: 28 });
  for (const note of notes) assert.notDeepEqual(Coffee.calculate({ roast: "medium", daysRoasted: 28, tastingNotes: [note] }), base, note);
  for (const roast of Coffee.ROASTS)
    for (const { recipe } of Coffee.compare({ roast, tastingNotes: notes })) {
      assert.ok(Object.values(recipe).flat().every(Number.isFinite));
      assert.equal(recipe.pulseTemps.length, recipe.pulses);
      assert.ok(Math.abs(recipe.grind) <= 16);
      assert.ok(recipe.bloomRatio <= 3);
    }
});

test("Celsius values and Fahrenheit rounding match the original recipe output", () => {
  assert.equal(Coffee.temperatures(97.5, "C"), 97.5);
  assert.equal(Coffee.temperatures(97.5, "F"), 208);
  assert.deepEqual(Coffee.temperatures([90, 93, 96], "F"), [194, 199, 205]);
  assert.throws(() => Coffee.calculate({ roast: "" }), /roast level/);
  assert.throws(() => Coffee.calculate({ roast: "medium", altitude: -1 }), /Altitude/);
});

test("match estimates match the original model", () => {
  for (const { home, away, year, expected } of fixtures.match) assert.deepEqual(Match.probabilities(home, away, year), expected);
});

test("match probabilities are normalised and retain home advantage and rating strength", () => {
  for (const home of [300, 1000, 1500, 2200])
    for (const away of [300, 1000, 1500, 2200]) {
      const p = Match.probabilities(home, away, 2026);
      assert.ok(p.every((value) => Number.isFinite(value) && value > 0 && value < 1));
      assert.ok(Math.abs(p.reduce((a, b) => a + b, 0) - 1) < 1e-12);
    }
  const equal = Match.probabilities(1500, 1500, 2026);
  assert.ok(equal[0] > equal[2]);
  assert.ok(Match.probabilities(1700, 1500, 2026)[0] > equal[0]);
});
